name: Trying out github actions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: 24f1002280@ds.study.iitm.ac.in
        run: echo "Hi, there"

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/demo
          key: cache-ff902f2

      - name: prime-cache-ff902f2
        run: |
          echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"

      - name: Create cache content (if cache missed)
        if: steps.cache-step.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.cache/demo
          echo "cached data" > ~/.cache/demo/data.txt
  
